vim.keymap.set("n", " ", "<Nop>", { silent = true, remap = false })
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<leader>w", ':w<CR>', { noremap = true, silent = true })
vim.keymap.set("n", "<leader>bn", '<cmd>bnext<CR>')
vim.keymap.set("n", "<leader>bp", '<cmd>bprevious<CR>')
vim.keymap.set("n", "<leader>bd", ':b#<bar>bd#<CR>')
vim.keymap.set("n", "<Tab>", ':bnext<CR>')
vim.keymap.set("n", "<S-Tab>", ':bprevious<cr>')
vim.keymap.set("n", "<C-d>", '<C-d>zz')
vim.keymap.set("n", "<C-u>", '<C-u>zz')
vim.keymap.set("n", ";", '<C-w>')
vim.keymap.set("n", ";d", '<C-d>zz')
vim.keymap.set("n", ";u", '<C-u>zz')
