vim.opt.nu = true
vim.opt.relativenumber = true 
vim.opt.autoindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.smarttab = true 
vim.opt.softtabstop = 4
vim.opt.mouse = "a"
vim.opt.errorbells = false 
vim.opt.wrap = false 
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.incsearch = true
